# Generated by Django 3.2.4 on 2022-07-15 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Carrito',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_nombre', models.CharField(max_length=30)),
                ('a_paterno', models.CharField(max_length=20)),
                ('num_contac', models.IntegerField()),
                ('rut', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medio_pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Medios de pago',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('img', models.ImageField(upload_to='productos')),
                ('desc', models.CharField(max_length=200)),
                ('tip_producto', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_nombre', models.CharField(max_length=20)),
                ('s_nombre', models.CharField(max_length=20)),
                ('a_paterno', models.CharField(max_length=20)),
                ('a_materno', models.CharField(max_length=20)),
                ('rut', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Vendedores',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.IntegerField()),
                ('total', models.IntegerField()),
                ('pedido', models.CharField(max_length=30)),
                ('carrito_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.carrito')),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('delivery_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.delivery')),
                ('pago_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medio_pago')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('vendedor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.vendedor')),
            ],
            options={
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.AddField(
            model_name='carrito',
            name='producto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto'),
        ),
    ]
