# Generated by Django 3.2.4 on 2022-06-03 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendedor',
            options={'verbose_name_plural': 'Vendedores'},
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='lista_prod',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='usuario_id',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='venta_id',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='usuario_id',
        ),
        migrations.AddField(
            model_name='carrito',
            name='producto_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.producto'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='desc',
            field=models.CharField(default=20, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='img',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tip_producto',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendedor',
            name='rut',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='producto_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.producto'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
