# Generated by Django 3.2.4 on 2022-06-05 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220603_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medio_pago',
            name='venta_id',
        ),
        migrations.AddField(
            model_name='venta',
            name='pago_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.medio_pago'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrito',
            name='producto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='desc',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='img',
            field=models.ImageField(upload_to='productos'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tip_producto',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='rut',
            field=models.CharField(max_length=20),
        ),
    ]
