# Generated by Django 3.2.4 on 2022-06-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_venta_pago_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='valor',
            field=models.IntegerField(default=1500),
            preserve_default=False,
        ),
    ]
