# Generated by Django 3.2.4 on 2022-06-05 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delivery_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='venta_id',
        ),
        migrations.AddField(
            model_name='venta',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.delivery'),
        ),
    ]
