# Generated by Django 3.2.4 on 2022-06-05 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_delivery_venta_delivery_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='cliente_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.cliente'),
            preserve_default=False,
        ),
    ]
