# Generated by Django 3.2.4 on 2022-06-06 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220605_1412'),
        ('core', '0010_auto_20220606_0532'),
    ]

    operations = [
    ]
