# Generated by Django 3.1.2 on 2022-07-13 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220605_1412'),
        ('core', '0010_auto_20220606_0532'),
    ]

    operations = [
    ]
