# Generated by Django 3.1.2 on 2022-07-14 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_20220713_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrito',
            options={'verbose_name_plural': 'Carrito'},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={},
        ),
    ]
