# Generated by Django 3.2.4 on 2022-06-07 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_cliente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name_plural': 'Cliente'},
        ),
    ]
