# Generated by Django 3.2.4 on 2022-06-07 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_cliente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='medio_pago',
            options={'verbose_name_plural': 'Medios de pago'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'verbose_name_plural': 'Ventas'},
        ),
    ]
