# Generated by Django 3.2.4 on 2022-06-12 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_20220607_0321'),
        ('core', '0015_auto_20220607_0018'),
    ]

    operations = [
    ]
