# Generated by Django 3.2.4 on 2022-06-13 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_merge_20220610_2301'),
        ('core', '0017_auto_20220612_1740'),
    ]

    operations = [
    ]
